; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=sm83 < %s | FileCheck %s
;
; SM83 ABI round-trip test.
; Calling convention:
;   - i8 arguments:  first in A, additional in B/C/D/E/H/L
;   - i16 arguments: first in BC, additional in DE/HL
;   - i8 return:     in A
;   - i16 return:    in HL
;   - Callee-save:   none (all registers are caller-save)
;   - Stack:         grows downward; local vars accessed via LD HL,SP+n / LD r,(HL)

; --- i8 argument pass-through (in A) ---
define i8 @pass_i8(i8 %x) {
; CHECK-LABEL: pass_i8:
; CHECK: ret
  ret i8 %x
}

; --- i8 return constant ---
define i8 @ret_i8_const() {
; CHECK-LABEL: ret_i8_const:
; CHECK: ld a, 42
; CHECK: ret
  ret i8 42
}

; --- i16 return constant ---
define i16 @ret_i16_const() {
; CHECK-LABEL: ret_i16_const:
; CHECK: ret
  ret i16 4660
}

; --- i8 add (uses A register for ALU) ---
define i8 @add_i8(i8 %x, i8 %y) {
; CHECK-LABEL: add_i8:
; CHECK: ret
  %r = add i8 %x, %y
  ret i8 %r
}

; --- i16 add ---
define i16 @add_i16(i16 %x, i16 %y) {
; CHECK-LABEL: add_i16:
; CHECK: ret
  %r = add i16 %x, %y
  ret i16 %r
}

; --- Local variable via fixed alloca (i8) ---
define i8 @local_i8(i8 %x) {
; CHECK-LABEL: local_i8:
; CHECK: ret
  %p = alloca i8
  store i8 %x, ptr %p
  %v = load i8, ptr %p
  ret i8 %v
}

; --- Local variable via fixed alloca (i16) ---
define i16 @local_i16(i16 %x) {
; CHECK-LABEL: local_i16:
; CHECK: ret
  %p = alloca i16
  store i16 %x, ptr %p
  %v = load i16, ptr %p
  ret i16 %v
}

; --- Nested call: callee computes x+1 ---
define i8 @add_one(i8 %x) {
; CHECK-LABEL: add_one:
; CHECK: ret
  %r = add i8 %x, 1
  ret i8 %r
}

define i8 @nested_call(i8 %x) {
; CHECK-LABEL: nested_call:
; CHECK: call
; CHECK: ret
  %r = call i8 @add_one(i8 %x)
  ret i8 %r
}

; --- i8 return from call ---
define i8 @call_ret_i8(i8 %x) {
; CHECK-LABEL: call_ret_i8:
; CHECK: call
; CHECK: ret
  %r = call i8 @pass_i8(i8 %x)
  ret i8 %r
}
