; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=sm83 < %s | FileCheck %s

; Test i8 addition.

define i8 @add_i8(i8 %a, i8 %b) {
  %result = add i8 %a, %b
  ret i8 %result
}

; Test i16 addition (uses ADD HL, rr).

define i16 @add_i16(i16 %a, i16 %b) {
  %result = add i16 %a, %b
  ret i16 %result
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
