; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=sm83 < %s | FileCheck %s

; Variable i8 left shift — loop: LD A,amt; OR A; skip if zero; SLA; DEC; JR NZ.

define i8 @shl_i8(i8 %a, i8 %b) {
  %result = shl i8 %a, %b
  ret i8 %result
}

define i8 @srl_i8(i8 %a, i8 %b) {
  %result = lshr i8 %a, %b
  ret i8 %result
}

define i8 @sra_i8(i8 %a, i8 %b) {
  %result = ashr i8 %a, %b
  ret i8 %result
}

; Variable i16 left shift — loop: SLA lo, RL hi (carry propagates lo→hi).

define i16 @shl_i16(i16 %a, i16 %b) {
  %result = shl i16 %a, %b
  ret i16 %result
}

; Variable i16 logical right shift — loop: SRL hi, RR lo (carry propagates hi→lo).

define i16 @srl_i16(i16 %a, i16 %b) {
  %result = lshr i16 %a, %b
  ret i16 %result
}

; Variable i16 arithmetic right shift — loop: SRA hi, RR lo.

define i16 @sra_i16(i16 %a, i16 %b) {
  %result = ashr i16 %a, %b
  ret i16 %result
}

; Constant i8 shifts — unrolled, no loop.

define i8 @shl_i8_const3(i8 %a) {
  %result = shl i8 %a, 3
  ret i8 %result
}

define i8 @srl_i8_const2(i8 %a) {
  %result = lshr i8 %a, 2
  ret i8 %result
}

define i8 @sra_i8_const4(i8 %a) {
  %result = ashr i8 %a, 4
  ret i8 %result
}

; Constant i16 shifts — unrolled, no loop.

define i16 @shl_i16_const2(i16 %a) {
  %result = shl i16 %a, 2
  ret i16 %result
}

define i16 @srl_i16_const1(i16 %a) {
  %result = lshr i16 %a, 1
  ret i16 %result
}

define i16 @sra_i16_const3(i16 %a) {
  %result = ashr i16 %a, 3
  ret i16 %result
}

; Shift-by-8 on i16 — byte-swap optimisation: 2 register moves, no loop.
; shl i16, 8: result_hi = src_lo, result_lo = 0.
; lshr i16, 8: result_lo = src_hi, result_hi = 0.

define i16 @shl_i16_const8(i16 %a) {
; CHECK-LABEL: shl_i16_const8:
; CHECK:       ld l, 0
; CHECK-NEXT:  ld h, c
; CHECK-NEXT:  ret
  %result = shl i16 %a, 8
  ret i16 %result
}

define i16 @srl_i16_const8(i16 %a) {
; CHECK-LABEL: srl_i16_const8:
; CHECK:       ld l, b
; CHECK-NEXT:  ld h, 0
; CHECK-NEXT:  ret
  %result = lshr i16 %a, 8
  ret i16 %result
}
